import {
  CascadeHazardChain,
  ImpactAsset,
  VulnerablePopulationReport,
  EmergencyResourceItem,
  ResponsePlanStep,
  SafeRouteItem,
  EvidenceConflictRecord
} from '../types/sihIntelligence';

export const MULTI_HAZARD_CHAINS: CascadeHazardChain[] = [
  {
    id: 'cascade-chain-tawang-01',
    title: 'Tawang Sela Corridor: Slope Failure to Highway Blockage & Border Cutoff',
    triggerEvent: 'Sustained monsoon downpour (>150mm/24h) + High pore-water pressure',
    activeSeverity: 'critical',
    riverBlockageRiskPct: 62,
    downstreamFloodRiskPct: 54,
    isolationRiskPct: 88,
    actionDirective: 'Pre-position heavy earthmoving equipment at Sela South Portal; divert civilian traffic to Dirang bypass.',
    nodes: [
      {
        id: 'cnode-1',
        title: 'Torrential Precipitation',
        category: 'Trigger',
        probabilityPct: 95,
        severity: 'critical',
        description: 'Atmospheric river event delivering 28 mm/h rainfall onto saturated colluvial mantle.',
        affectedLocations: ['Sela Top', 'Baisakhi', 'Jaswant Garh'],
      },
      {
        id: 'cnode-2',
        title: 'Rotational Slope Shear',
        category: 'Primary Hazard',
        probabilityPct: 86,
        severity: 'critical',
        description: 'Shear slip plane activating along fractured gneiss bedrock boundary at 48° incline.',
        affectedLocations: ['NH-13 Km 42-45', 'Sela Pass South'],
      },
      {
        id: 'cnode-3',
        title: 'Highway 13 Total Blockage',
        category: 'Secondary Cascade',
        probabilityPct: 91,
        severity: 'critical',
        description: 'Estimated 22,000 m³ rock and debris deposition across 380 meters of strategic highway.',
        affectedLocations: ['NH-13 Lifeline Highway'],
      },
      {
        id: 'cnode-4',
        title: 'Tawang Valley Civil & Strategic Isolation',
        category: 'Infrastructure Impact',
        probabilityPct: 88,
        severity: 'high',
        description: 'Cutoff of primary fuel, food ration, and medical transit; army logistics disrupted.',
        affectedLocations: ['Tawang Town', 'Jang', 'Kitpi Sub-division'],
      },
      {
        id: 'cnode-5',
        title: 'Critical Emergency Medical Access Delay',
        category: 'Societal Impact',
        probabilityPct: 79,
        severity: 'high',
        description: 'Ambulance transfer time to Tezpur Base Hospital increased from 6 hours to infinite (air-evac only).',
        affectedLocations: ['District Civil Hospital Tawang', 'Nurang Community Health Centre'],
      },
    ],
  },
  {
    id: 'cascade-chain-tupul-02',
    title: 'Ijei River Valley: Landslide Debris Dam to Catastrophic Flash Inundation',
    triggerEvent: 'Deep-seated hill cut failure surcharging into Ijei riverbed',
    activeSeverity: 'critical',
    riverBlockageRiskPct: 89,
    downstreamFloodRiskPct: 84,
    isolationRiskPct: 92,
    actionDirective: 'Immediate siren broadcast to downstream riparian hamlets; breach mitigation team on standby.',
    nodes: [
      {
        id: 'cnode-11',
        title: 'Excavation Toe Debuttressing',
        category: 'Trigger',
        probabilityPct: 90,
        severity: 'critical',
        description: 'Railway cutting overburden loosened by moisture saturation and blasting fissures.',
        affectedLocations: ['Tupul Yard', 'Marangching Slope'],
      },
      {
        id: 'cnode-12',
        title: 'Massive Debris Avalanche',
        category: 'Primary Hazard',
        probabilityPct: 88,
        severity: 'critical',
        description: 'Over 80,000 metric tons of mudstone and gravel sliding into the river gorge.',
        affectedLocations: ['Ijei River Gorge'],
      },
      {
        id: 'cnode-13',
        title: 'Artificial Landslide Dam Formation',
        category: 'Secondary Cascade',
        probabilityPct: 84,
        severity: 'critical',
        description: 'Debris completely blocks Ijei river flow; water level rising at 1.4 meters per hour behind the barrier.',
        affectedLocations: ['Tupul Dam Reservoir'],
      },
      {
        id: 'cnode-14',
        title: 'Downstream Flash Flood Outburst',
        category: 'Infrastructure Impact',
        probabilityPct: 78,
        severity: 'critical',
        description: 'Impending dam breach threatens to release high-velocity mud wall towards low-lying settlements.',
        affectedLocations: ['Charoi Chagotlong', 'Khongsang', 'Noney Lower Valley'],
      },
      {
        id: 'cnode-15',
        title: 'Bridges & Railway Subgrade Scour',
        category: 'Societal Impact',
        probabilityPct: 82,
        severity: 'high',
        description: 'Loss of Bailey bridges and track piers along Jiribam-Imphal line.',
        affectedLocations: ['Bridge 44', 'NH-37 Connecting Spans'],
      },
    ],
  },
];

export const IMPACT_ASSETS_TAWANG: ImpactAsset[] = [
  {
    id: 'asset-1',
    name: 'Sela Pass South Portal Highway Bridge',
    type: 'bridge',
    distanceFromHazardKm: 0.4,
    populationOrCapacity: 450,
    status: 'threatened',
    coordinates: [27.5028, 92.0984],
  },
  {
    id: 'asset-2',
    name: 'Jang Border Village Community',
    type: 'village',
    distanceFromHazardKm: 2.1,
    populationOrCapacity: 1840,
    status: 'threatened',
    coordinates: [27.5741, 91.9842],
  },
  {
    id: 'asset-3',
    name: 'Government Higher Secondary School Jang',
    type: 'school',
    distanceFromHazardKm: 2.3,
    populationOrCapacity: 340,
    status: 'evacuate',
    coordinates: [27.576, 91.985],
  },
  {
    id: 'asset-4',
    name: 'Nurang Sub-District Health Centre',
    type: 'hospital',
    distanceFromHazardKm: 3.8,
    populationOrCapacity: 60,
    status: 'operational',
    coordinates: [27.552, 92.03],
  },
  {
    id: 'asset-5',
    name: 'NH-13 Sela Military Logistics Corridor',
    type: 'road',
    distanceFromHazardKm: 0.1,
    populationOrCapacity: 1200,
    status: 'blocked',
    coordinates: [27.505, 92.095],
  },
  {
    id: 'asset-6',
    name: 'BSNL Sela Optical Fiber Repeater Tower',
    type: 'telecom',
    distanceFromHazardKm: 0.8,
    populationOrCapacity: 4500,
    status: 'threatened',
    coordinates: [27.508, 92.1],
  },
];

export const VULNERABLE_POPULATION_ZONES: VulnerablePopulationReport[] = [
  {
    zoneId: 'ZONE-TAW-01',
    zoneName: 'Jang & Sela Foothills Cluster',
    totalPopulation: 2180,
    childrenCount: 420,
    elderlyCount: 310,
    criticalFacilitiesCount: 4,
    roadAccessStatus: 'COMPROMISED',
    exposureScore: 84,
    priorityRanking: 1,
  },
  {
    zoneId: 'ZONE-NON-02',
    zoneName: 'Noney Tupul River Basin Settlements',
    totalPopulation: 3450,
    childrenCount: 680,
    elderlyCount: 490,
    criticalFacilitiesCount: 6,
    roadAccessStatus: 'SEVERELY BLOCKED',
    exposureScore: 89,
    priorityRanking: 2,
  },
  {
    zoneId: 'ZONE-DIM-03',
    zoneName: 'Haflong Railway Sub-Gorge Sector',
    totalPopulation: 4200,
    childrenCount: 890,
    elderlyCount: 520,
    criticalFacilitiesCount: 5,
    roadAccessStatus: 'COMPROMISED',
    exposureScore: 78,
    priorityRanking: 3,
  },
  {
    zoneId: 'ZONE-GAN-04',
    zoneName: '13th Mile Nathula Pilgrim Enclave',
    totalPopulation: 950,
    childrenCount: 110,
    elderlyCount: 140,
    criticalFacilitiesCount: 2,
    roadAccessStatus: 'OPEN',
    exposureScore: 68,
    priorityRanking: 4,
  },
];

export const EMERGENCY_RESOURCES: EmergencyResourceItem[] = [
  {
    id: 'res-1',
    type: 'Rescue Team (NDRF)',
    unitName: '12th Bn NDRF Task Force Alpha (32 Pers)',
    stationBase: 'Doimukh Base Station',
    currentStatus: 'Dispatched',
    assignedZone: 'ZONE-TAW-01 (Tawang Sela)',
    etaMinutes: 45,
  },
  {
    id: 'res-2',
    type: 'Heavy Excavator',
    unitName: 'BRO Project Vartak Hydraulic Breaker 210',
    stationBase: 'Baisakhi Maintenance Depot',
    currentStatus: 'En Route',
    assignedZone: 'NH-13 Km 44 Debris Site',
    etaMinutes: 20,
  },
  {
    id: 'res-3',
    type: 'Ambulance',
    unitName: '4x4 Advanced Life Support Ambulance 08',
    stationBase: 'Jang Community Health Post',
    currentStatus: 'On Site',
    assignedZone: 'Jang Primary Evacuation Shelter',
    etaMinutes: 0,
  },
  {
    id: 'res-4',
    type: 'Emergency Medical Unit',
    unitName: 'Army Field Triage & Trauma Station (12 Beds)',
    stationBase: 'Nurang Staging Base',
    currentStatus: 'Available',
    assignedZone: 'ZONE-TAW-01',
    etaMinutes: 30,
  },
  {
    id: 'res-5',
    type: 'Air Evac Helicopter',
    unitName: 'IAF Mi-17 V5 SAR Helo (Gauhati Detachment)',
    stationBase: 'Tezpur Air Force Station',
    currentStatus: 'Available',
    assignedZone: 'High-Altitude Emergency Reserve',
    etaMinutes: 65,
  },
  {
    id: 'res-6',
    type: 'Relief Distribution Truck',
    unitName: 'Disaster Management Ration & Water Carrier 04',
    stationBase: 'Dirang Supply Depot',
    currentStatus: 'En Route',
    assignedZone: 'Jang Community Shelter',
    etaMinutes: 50,
  },
];

export const RESCUE_MISSION_PLAN_TAWANG: ResponsePlanStep[] = [
  {
    stepNumber: 1,
    title: 'Deploy Automated Siren & Cell Broadcast Alert',
    agency: 'State Disaster Management Authority (SDMA)',
    priority: 'Immediate',
    status: 'Completed',
    instructions: 'Broadcast vernacular Monpa/Hindi/English warning message to 2,180 residents in Sela and Jang valley within 3km radius.',
  },
  {
    stepNumber: 2,
    title: 'Physical Traffic Barrier at Baisakhi & Sela South Portal',
    agency: 'Border Roads Organisation (BRO) & Traffic Police',
    priority: 'Immediate',
    status: 'In Progress',
    instructions: 'Close NH-13 between Km 38 and Km 48 to all non-military vehicles. Halt ascending commercial convoy.',
  },
  {
    stepNumber: 3,
    title: 'Precautionary Evacuation of Jang Higher Secondary School',
    agency: 'District Administration & Local Volunteers',
    priority: 'Urgent',
    status: 'In Progress',
    instructions: 'Move 340 students and staff to elevated Community Hall safe shelter at +120m ridge grade.',
  },
  {
    stepNumber: 4,
    title: 'Position Heavy Excavator & Rock Clearing Breakers',
    agency: 'BRO Project Vartak',
    priority: 'Urgent',
    status: 'In Progress',
    instructions: 'Stage 2 hydraulic excavators at Km 41 safety turnout ready to clear toe spill within 15 minutes of rupture.',
  },
  {
    stepNumber: 5,
    title: 'Activate Dirang Old Mule Bypass Safe Emergency Route',
    agency: 'District Magistrate & Rural Works Dept',
    priority: 'Urgent',
    status: 'Pending',
    instructions: 'Clear gravel slide on secondary all-weather 4x4 bypass to maintain critical medical supply route.',
  },
  {
    stepNumber: 6,
    title: 'Place 4x4 Medical Units on Standby at Nurang',
    agency: 'Directorate of Health Services',
    priority: 'Standard',
    status: 'Pending',
    instructions: 'Prepare trauma triage supplies and oxygen cylinders for high-altitude hypothermia and blunt injury.',
  },
  {
    stepNumber: 7,
    title: 'Continuous InSAR & Accelerometer Drone Overflight',
    agency: 'National Remote Sensing Centre (NRSC / AI Station)',
    priority: 'Standard',
    status: 'Pending',
    instructions: 'Track tension crack aperture rate every 30 minutes to detect progressive rupture acceleration.',
  },
];

export const SAFE_ROUTES_TAWANG: SafeRouteItem[] = [
  {
    routeId: 'route-nh13-main',
    name: 'NH-13 Sela Pass Highway (Primary Trunk Route)',
    distanceKm: 42,
    estTimeMinutes: 75,
    safetyRating: 'Blocked / Impassable',
    pathDescription: 'Closed at Km 44 due to active slope creep (7.2 mm/day) and mud deposit threat. Impassable.',
    isRecommended: false,
  },
  {
    routeId: 'route-dirang-bypass',
    name: 'Dirang-Lubrang High Ridge Forest Bypass',
    distanceKm: 58,
    estTimeMinutes: 110,
    safetyRating: 'Safe Corridor',
    pathDescription: 'All-weather stabilized gravel bypass traversing competent granite ridge crest. 100% free of landslide and flood risk.',
    isRecommended: true,
  },
  {
    routeId: 'route-mandra-river-track',
    name: 'Mandra Lower River Track',
    distanceKm: 34,
    estTimeMinutes: 90,
    safetyRating: 'Caution Required',
    pathDescription: 'Low-elevation path along river drainage. High risk of debris inundation if river damming occurs.',
    isRecommended: false,
  },
];

export const EVIDENCE_CONFLICT_RECORDS: EvidenceConflictRecord[] = [
  {
    id: 'conflict-01',
    location: 'Sela Pass Km 44.2 Hill Shoulder',
    satelliteObservation: 'Sentinel-2 optical pass: Cloud obscured; InSAR reports baseline 7.2mm LOS subsidence.',
    fieldReportObservation: 'Village Headman & BRO Patrol report 45-meter-long continuous tension crack (width 12cm) across road shoulder.',
    conflictStatus: 'CRITICAL CONFLICT',
    systemActionDirective: 'Field report verified by GPS photos; escalated inspection priority to Level 4 (Immediate Road Closure).',
    escalatedPriority: true,
  },
  {
    id: 'conflict-02',
    location: 'Noney Tupul River Bed Sector',
    satelliteObservation: 'Optical satellite detects no major ponding (data captured 24 hours ago).',
    fieldReportObservation: 'Citizen report with geo-tagged video shows river water turning muddy brown and rising 2 feet.',
    conflictStatus: 'MODERATE DISCREPANCY',
    systemActionDirective: 'Prioritized live drone aerial verification; warned downstream settlements of potential debris dam.',
    escalatedPriority: true,
  },
];
