import {
  SlopeMemoryRecord,
  DisasterFingerprint,
  WhyNowExplanation,
  DataQualityReport,
  RiskFusionWeights
} from '../types/sihIntelligence';
import { LandslideStation } from '../types/landslide';

export const DEFAULT_RISK_WEIGHTS: RiskFusionWeights = {
  rainfall: 0.30,
  soilMoisture: 0.20,
  slope: 0.20,
  historicalRisk: 0.15,
  terrainInstability: 0.10,
  exposure: 0.05,
};

export const INITIAL_SLOPE_REGISTRY: SlopeMemoryRecord[] = [
  {
    slopeId: 'TAW-042',
    slopeName: 'Tawang Sela Pass Military Highway Corridor',
    stationId: 'tawang-pass-01',
    state: 'Arunachal Pradesh',
    district: 'Tawang',
    coordinates: [27.5028, 92.0984],
    elevationM: 4170,
    slopeAngleDeg: 48,
    geologyType: 'Fractured Biotite Gneiss & Glacial Till',
    historicalDisasterYear: 2021,
    historicalEventName: 'Sela Pass Monsoon Slope Breach & Road Cutoff',
    historicalRainfallMm: 162,
    historicalSoilMoisturePct: 87,
    historicalGroundMovementMm: 8.4,
    historicalPorePressureKpa: 76,
    historicalImpactDescription: '3.2km BRO military convoy road buried under 14,000 m³ fractured debris; 2 army trucks trapped, 4 bridges isolated.',
    historicalFatalities: 3,
    currentRainfallMm: 155,
    currentSoilMoisturePct: 84,
    currentGroundMovementMm: 7.2,
    currentPorePressureKpa: 71,
    similarityScorePct: 91,
    similarityFactors: [
      {
        factor: '24h Cumulative Precipitation',
        historicalVal: '162 mm',
        currentVal: '155 mm',
        matchPct: 95.7,
        contribution: '+38% similarity driver (monsoon saturation profile matches 2021 pre-failure threshold)',
      },
      {
        factor: 'Volumetric Soil Saturation',
        historicalVal: '87%',
        currentVal: '84%',
        matchPct: 96.5,
        contribution: '+28% similarity driver (pore water lubricating shear boundary)',
      },
      {
        factor: 'Slope Inclinometer & Creep',
        historicalVal: '8.4 mm/day',
        currentVal: '7.2 mm/day',
        matchPct: 85.7,
        contribution: '+18% similarity driver (accelerating downslope plastic creep)',
      },
      {
        factor: 'Pore Water Pressure',
        historicalVal: '76 kPa',
        currentVal: '71 kPa',
        matchPct: 93.4,
        contribution: '+9% similarity driver (hydrostatic uplift reducing normal stress)',
      },
    ],
    verdictText: 'Current environmental conditions strongly resemble historical 2021 failure patterns (91% match). High likelihood of shear toe rupture within 6-18 hours.',
  },
  {
    slopeId: 'GAN-018',
    slopeName: 'Gangtok-Nathula National Highway 310 Cut',
    stationId: 'gangtok-nathula-02',
    state: 'Sikkim',
    district: 'East Sikkim',
    coordinates: [27.3889, 88.6138],
    elevationM: 3100,
    slopeAngleDeg: 44,
    geologyType: 'Daling Quartzite Schist with Colluvial Overburden',
    historicalDisasterYear: 2023,
    historicalEventName: '13th Mile Debris Flow & Teesta Surge',
    historicalRainfallMm: 185,
    historicalSoilMoisturePct: 92,
    historicalGroundMovementMm: 11.2,
    historicalPorePressureKpa: 84,
    historicalImpactDescription: '7 tourists stranded, 140m highway segment washed down into gorge; BRO clearance took 48 hours.',
    historicalFatalities: 7,
    currentRainfallMm: 172,
    currentSoilMoisturePct: 88,
    currentGroundMovementMm: 9.8,
    currentPorePressureKpa: 79,
    similarityScorePct: 89,
    similarityFactors: [
      {
        factor: 'High-Altitude Cloudburst Rain',
        historicalVal: '185 mm',
        currentVal: '172 mm',
        matchPct: 93.0,
        contribution: 'Excess surface runoff causing active channel scouring',
      },
      {
        factor: 'Pore Pressure Infiltration',
        historicalVal: '84 kPa',
        currentVal: '79 kPa',
        matchPct: 94.0,
        contribution: 'Shear strength degradation on steep mountain shoulder',
      },
    ],
    verdictText: 'Conditions reflect 89% similarity to the 2023 13th Mile surge. Colluvial overburden is nearing dynamic liquefaction threshold.',
  },
  {
    slopeId: 'DIM-009',
    slopeName: 'Dima Hasao Hill Railway & NH-54E Gorge',
    stationId: 'dima-hasao-03',
    state: 'Assam',
    district: 'Dima Hasao',
    coordinates: [25.1852, 93.0245],
    elevationM: 780,
    slopeAngleDeg: 38,
    geologyType: 'Tertiary Sandstone-Shale Alternation with Mudstone Slaking',
    historicalDisasterYear: 2022,
    historicalEventName: 'New Haflong Railway Station Submersion & Mudslide',
    historicalRainfallMm: 215,
    historicalSoilMoisturePct: 95,
    historicalGroundMovementMm: 14.5,
    historicalPorePressureKpa: 89,
    historicalImpactDescription: 'Haflong railway station covered under 6ft mud, train coaches overturned, southern Assam cutoff for 2 months.',
    historicalFatalities: 12,
    currentRainfallMm: 195,
    currentSoilMoisturePct: 91,
    currentGroundMovementMm: 12.1,
    currentPorePressureKpa: 82,
    similarityScorePct: 93,
    similarityFactors: [
      {
        factor: 'Unremitting Monsoon Deluge',
        historicalVal: '215 mm',
        currentVal: '195 mm',
        matchPct: 90.7,
        contribution: 'Complete shale-layer slaking and subgrade liquefaction',
      },
      {
        factor: 'Soil Saturation Saturation Index',
        historicalVal: '95%',
        currentVal: '91%',
        matchPct: 95.8,
        contribution: 'Water table has breached surface grade at toe of railway cutting',
      },
    ],
    verdictText: 'Extreme 93% correlation with 2022 New Haflong disaster. Severe mudflow risk across rail cuttings and NH-54E road corridor.',
  },
  {
    slopeId: 'KOH-005',
    slopeName: 'Kohima Bypass Old KMC Mudslide Zone',
    stationId: 'kohima-bypass-04',
    state: 'Nagaland',
    district: 'Kohima',
    coordinates: [25.6751, 94.1086],
    elevationM: 1444,
    slopeAngleDeg: 36,
    geologyType: 'Disang Shales with High Swelling Smectite Clay',
    historicalDisasterYear: 2018,
    historicalEventName: 'KMC Solid Waste & National Highway Slump',
    historicalRainfallMm: 148,
    historicalSoilMoisturePct: 83,
    historicalGroundMovementMm: 6.8,
    historicalPorePressureKpa: 65,
    historicalImpactDescription: 'NH-2 Lifeline highway sunk by 12 meters; supply trucks stranded for 11 days.',
    historicalFatalities: 2,
    currentRainfallMm: 138,
    currentSoilMoisturePct: 79,
    currentGroundMovementMm: 5.9,
    currentPorePressureKpa: 60,
    similarityScorePct: 86,
    similarityFactors: [
      {
        factor: 'Cumulative Infiltration',
        historicalVal: '148 mm',
        currentVal: '138 mm',
        matchPct: 93.2,
        contribution: 'Expansive Disang shale softening',
      },
    ],
    verdictText: 'High 86% match with 2018 NH-2 road subsidence. Sinking zone active along 450 meters.',
  },
  {
    slopeId: 'TUP-017',
    slopeName: 'Noney Tupul Railway Construction Base Camp',
    stationId: 'noney-tupul-05',
    state: 'Manipur',
    district: 'Noney',
    coordinates: [24.8167, 93.6333],
    elevationM: 650,
    slopeAngleDeg: 42,
    geologyType: 'Shattered Siltstone & Uncompacted Excavated Overburden',
    historicalDisasterYear: 2022,
    historicalEventName: 'Tupul Mega-Debris Avalanche & Ijei River Damming',
    historicalRainfallMm: 230,
    historicalSoilMoisturePct: 96,
    historicalGroundMovementMm: 18.0,
    historicalPorePressureKpa: 94,
    historicalImpactDescription: 'Territorial Army camp crushed by massive hill collapse; Ijei river blocked forming an artificial lake, catastrophic downstream flood threat.',
    historicalFatalities: 58,
    currentRainfallMm: 210,
    currentSoilMoisturePct: 92,
    currentGroundMovementMm: 15.5,
    currentPorePressureKpa: 88,
    similarityScorePct: 94,
    similarityFactors: [
      {
        factor: 'Torrential Precipitation Index',
        historicalVal: '230 mm',
        currentVal: '210 mm',
        matchPct: 91.3,
        contribution: 'Overburden surcharge reached critical liquidity limit',
      },
      {
        factor: 'Extensometer Displacement Surge',
        historicalVal: '18.0 mm',
        currentVal: '15.5 mm',
        matchPct: 86.1,
        contribution: 'Deep rotational slip surface formed along bedding planes',
      },
    ],
    verdictText: 'Critical 94% similarity to the 2022 Tupul disaster. Catastrophic potential for debris damming Ijei river channel.',
  },
  {
    slopeId: 'CHU-033',
    slopeName: 'Chungthang Dam & Teesta Stage III Valley',
    stationId: 'chungthang-sikkim-06',
    state: 'Sikkim',
    district: 'Mangan',
    coordinates: [27.6042, 88.6447],
    elevationM: 1790,
    slopeAngleDeg: 52,
    geologyType: 'Granite Gneiss Fault Fracture with Moraine Colluvium',
    historicalDisasterYear: 2023,
    historicalEventName: 'South Lhonak GLOF & Chungthang Dam Breach',
    historicalRainfallMm: 198,
    historicalSoilMoisturePct: 94,
    historicalGroundMovementMm: 16.0,
    historicalPorePressureKpa: 92,
    historicalImpactDescription: 'Glacial lake burst surge swept away Chungthang dam, 14 military bridges destroyed, entire valley disconnected.',
    historicalFatalities: 42,
    currentRainfallMm: 182,
    currentSoilMoisturePct: 89,
    currentGroundMovementMm: 13.8,
    currentPorePressureKpa: 85,
    similarityScorePct: 92,
    similarityFactors: [
      {
        factor: 'High Altitude Precipitation & Melt',
        historicalVal: '198 mm',
        currentVal: '182 mm',
        matchPct: 91.9,
        contribution: 'Excess moraine erosion & hydro-static dam pressure',
      },
    ],
    verdictText: '92% similarity to 2023 Teesta disaster pattern. Severe downstream surge alert active.',
  },
];

export function getDisasterFingerprint(slope: SlopeMemoryRecord): DisasterFingerprint {
  return {
    slopeId: slope.slopeId,
    slopeName: slope.slopeName,
    overallSimilarityPct: slope.similarityScorePct,
    explanation: slope.verdictText,
    metrics: [
      {
        name: 'Rainfall Load',
        currentValue: Math.min(100, Math.round((slope.currentRainfallMm / 200) * 100)),
        historicalValue: Math.min(100, Math.round((slope.historicalRainfallMm / 200) * 100)),
        unit: 'mm/24h',
        rawCurrent: slope.currentRainfallMm,
        rawHistorical: slope.historicalRainfallMm,
      },
      {
        name: 'Soil Saturation',
        currentValue: slope.currentSoilMoisturePct,
        historicalValue: slope.historicalSoilMoisturePct,
        unit: '% VWC',
        rawCurrent: slope.currentSoilMoisturePct,
        rawHistorical: slope.historicalSoilMoisturePct,
      },
      {
        name: 'Slope Gradient',
        currentValue: Math.min(100, Math.round((slope.slopeAngleDeg / 60) * 100)),
        historicalValue: Math.min(100, Math.round((slope.slopeAngleDeg / 60) * 100)),
        unit: 'deg',
        rawCurrent: slope.slopeAngleDeg,
        rawHistorical: slope.slopeAngleDeg,
      },
      {
        name: 'Pore Pressure',
        currentValue: Math.min(100, Math.round((slope.currentPorePressureKpa / 100) * 100)),
        historicalValue: Math.min(100, Math.round((slope.historicalPorePressureKpa / 100) * 100)),
        unit: 'kPa',
        rawCurrent: slope.currentPorePressureKpa,
        rawHistorical: slope.historicalPorePressureKpa,
      },
      {
        name: 'Ground Creep',
        currentValue: Math.min(100, Math.round((slope.currentGroundMovementMm / 20) * 100)),
        historicalValue: Math.min(100, Math.round((slope.historicalGroundMovementMm / 20) * 100)),
        unit: 'mm/day',
        rawCurrent: slope.currentGroundMovementMm,
        rawHistorical: slope.historicalGroundMovementMm,
      },
      {
        name: 'Satellite Change',
        currentValue: 78,
        historicalValue: 85,
        unit: '% veg loss',
        rawCurrent: 78,
        rawHistorical: 85,
      },
      {
        name: 'Population Exposure',
        currentValue: 82,
        historicalValue: 80,
        unit: 'exposure index',
        rawCurrent: 82,
        rawHistorical: 80,
      },
      {
        name: 'Historical Susceptibility',
        currentValue: 88,
        historicalValue: 92,
        unit: 'GSI index',
        rawCurrent: 88,
        rawHistorical: 92,
      },
    ],
  };
}

export function computeWhyNowExplanation(
  station: LandslideStation | null,
  simulatedRainDelta: number = 0
): WhyNowExplanation {
  const currentRain = (station?.telemetry?.rainfall24hMm || 45) + simulatedRainDelta;
  const currentMoisture = Math.min(99, (station?.telemetry?.soilMoisturePct || 65) + simulatedRainDelta * 0.2);
  const currentDisp = (station?.telemetry?.displacementMm || 2.4) + simulatedRainDelta * 0.05;

  const yesterdayRisk = 46;
  const rawScore = 78 + Math.round(simulatedRainDelta * 0.2);
  const currentRisk = Math.min(99, Math.max(20, rawScore));
  const delta = currentRisk - yesterdayRisk;

  return {
    previousRiskScore: yesterdayRisk,
    currentRiskScore: currentRisk,
    deltaScore: delta,
    primaryExplanation:
      'Risk escalated significantly (+32 pts in 24h) because sustained monsoon infiltration pushed pore-water pressure past 70 kPa, while slope displacement accelerated to 7.2 mm/day matching the 2021 pre-collapse signature.',
    contributions: [
      {
        factor: '24h Cumulative Precipitation',
        previousVal: 48,
        currentVal: Math.round(currentRain),
        scoreContribution: +28,
        severity: 'critical',
      },
      {
        factor: 'Soil Saturation & Pore Pressure',
        previousVal: 52,
        currentVal: Math.round(currentMoisture),
        scoreContribution: +17,
        severity: 'high',
      },
      {
        factor: 'Slope Incline & Shear Stress',
        previousVal: 48,
        currentVal: 48,
        scoreContribution: +18,
        severity: 'high',
      },
      {
        factor: 'Historical Disaster Memory Match',
        previousVal: 35,
        currentVal: 91,
        scoreContribution: +12,
        severity: 'high',
      },
      {
        factor: 'Anthropogenic Toe Cut / Road Excavation',
        previousVal: 40,
        currentVal: 65,
        scoreContribution: +5,
        severity: 'moderate',
      },
      {
        factor: 'Critical Asset & Population Exposure',
        previousVal: 42,
        currentVal: 74,
        scoreContribution: +2,
        severity: 'moderate',
      },
    ],
    finalScoreText: `${currentRisk}/100 [HIGH / IMMINENT FAILURE]`,
  };
}

export function getDataQualityScorecard(): DataQualityReport {
  return {
    overallConfidencePct: 88,
    confidenceGrade: 'HIGH',
    confidenceExplanation:
      'Confidence is strong (88%) driven by live IMD Doppler feeds, verified GSI slope morphology, and calibrated MEMS inclinometers. Confidence reduced slightly (-12%) because optical satellite imagery has 40% cloud cover over high altitude passes.',
    streams: [
      {
        streamName: 'Weather Telemetry (IMD / Open-Meteo)',
        status: 'GREEN',
        freshnessText: 'Live (2 mins ago)',
        sampleRate: '15 min intervals',
        statusLabel: 'EXCELLENT',
        notes: 'Calibrated tipping bucket gauges with Doppler radar confirmation.',
      },
      {
        streamName: 'Terrain & DEM (CartoDEM 10m)',
        status: 'GREEN',
        freshnessText: 'High-Res Elevation Mesh',
        sampleRate: 'Static baseline',
        statusLabel: 'EXCELLENT',
        notes: 'Hydrologically conditioned digital elevation model.',
      },
      {
        streamName: 'Historical Landslide Memory (GSI / NDMA)',
        status: 'GREEN',
        freshnessText: 'Verified 1974-2024 Records',
        sampleRate: '128 geo-referenced incidents',
        statusLabel: 'EXCELLENT',
        notes: 'Full failure kinematics and consequence logs available.',
      },
      {
        streamName: 'Satellite Synthetic Aperture Radar (InSAR)',
        status: 'GREEN',
        freshnessText: 'Sentinel-1 pass 18h ago',
        sampleRate: '6-day orbit repeat',
        statusLabel: 'EXCELLENT',
        notes: 'Interferometric coherence indicates 7.2mm line-of-sight subsidence.',
      },
      {
        streamName: 'Citizen & Field Observer Reports',
        status: 'YELLOW',
        freshnessText: '14 reports in last 6 hours',
        sampleRate: 'Crowdsourced stream',
        statusLabel: 'LIMITED',
        notes: 'Cluster verification pending for 3 crowdsourced road blockage reports.',
      },
      {
        streamName: 'Subsurface Piezometer & Soil Moisture',
        status: 'YELLOW',
        freshnessText: 'Active on 14/16 stations',
        sampleRate: 'Hourly mesh',
        statusLabel: 'LIMITED',
        notes: '2 remote high-altitude nodes running on LoRa solar reserve.',
      },
    ],
  };
}
